name: Dungeons
version: ${version}
main: me.Eggses.dungeons.Dungeons
api-version: '1.21'
load: STARTUP
authors: [ Eggses ]
description: Dungeons

commands:
  dungeons:
    description: Dungeon base command
    usage: /dungeons
    permission: dungeons.command.base

permissions:
  # =====================================
  # Base command
  # =====================================
  dungeons.command.base:
    description: Allows use of /dungeons
    default: true

  # =====================================
  # Core subcommands
  # =====================================
  dungeons.command.reload:
    description: Allows use of /dungeons reload
    default: op

  dungeons.command.trigger:
    description: Allows use of /dungeons trigger
    default: op

  dungeons.command.give:
    description: Allows use of /dungeons give
    default: op

  dungeons.command.destroy:
    description: Allows use of /dungeons destroy
    default: op

  # =====================================
  # Command Block
  # =====================================
  dungeons.command.trigger.commandblock:
    description: Allows /dungeons trigger to be executed by command blocks
    default: op
