name: Dungeons
version: ${version}
main: me.Eggses.dungeons.Dungeons
api-version: '1.21'
authors: [ Eggses ]
description: Dungeons

commands:
  dungeons:
    description: Dungeon base command
    usage: /dungeons
    permission: dungeons.command.base

permissions:
  # =====================================
  # Base command
  # =====================================
  dungeons.command.base:
    description: Allows use of /dungeons
    default: true

  # =====================================
  # Core subcommands
  # =====================================
  dungeons.command.reload:
    description: Allows use of /dungeons reload
    default: op

  dungeons.command.trigger:
    description: Allows use of /dungeons trigger
    default: op

  dungeons.command.give:
    description: Allows use of /dungeons give
    default: op

  dungeons.command.give.others:
    description: Allows use of /dungeons give [player]
    default: op
    children:
      dungeons.command.give: true

  dungeons.command.destroy:
    description: Allows use of /dungeons destroy
    default: op

  dungeons.command.stats:
    description: Allows use of /dungeons stats
    default: op