name: Dungeons
version: ${version}
main: me.Eggses.dungeons.Dungeons
api-version: '1.21'
load: STARTUP
authors: [ Eggses ]
description: Dungeons

commands:
  dungeons:
    description: Dungeon Base Command
    usage: /dungeons
    permission: dungeons.commands

permissions:
  dungeons.commands:
    description: Permission for /dungeons
    default: op
  dungeons.commands.admin.cmdblock.trigger:
    description: Permission for /dungeons trigger [arg1]
    default: op
  dungeons.commands.admin.destroy:
    description: Permission for /dungeons destroy <ALL | World_Name>
    default: op